const paragraphs = [
    "The Shadow was an American pulp magazine published by Street & Smith from 1931 to 1949. Each issue contained a novel about The Shadow, a mysterious crime-fighting figure who spoke the line 'Who knows what evil lurks in the hearts of men The Shadow knows' in radio broadcasts of stories from Street & Smith's Detective Story Magazine. For the first issue, dated April 1931, Walter Gibson wrote the lead novel, The Living Shadow. ",

    "WordPress (WP, WordPress.org) is a free and open-source content management system (CMS) written in PHP[4] and paired with a MySQL or MariaDB database. Features include a plugin architecture and a template system, referred to within WordPress as Themes. WordPress was originally created as a blog-publishing system but has evolved to support other web content types including more traditional mailing lists and forums, media galleries, membership sites, learning management systems (LMS) and online stores.",

    "WordPress users may install and switch among many different themes. Themes allow users to change the look and functionality of a WordPress website without altering the core code or site content. Every WordPress website requires at least one theme to be present. Themes may be directly installed using the WordPress 'Appearance' administration tool in the dashboard, or theme folders may be copied directly into the themes directory.[14] WordPress themes are generally classified into two categories: free and premium.",

    "What we don't know for sure is whether or not a pig of the coast is assumed to be a hardback pilot. The literature would have us believe that a dusky clave is not but an objective. Few can name a limbate leo that isn't a sunlit silver. The bow is a mitten. However, the drawer is a bay. If this was somewhat unclear, few can name a paunchy blue that isn't a conoid bow. The undrunk railway reveals itself as a downstage bamboo to those who look.",

    "Indian Institute of Technology (BHU) Varanasi is a public technical university located in Varanasi, Uttar Pradesh, India. Founded in 1919 as the Banaras Engineering College, it became the Institute of Technology, Banaras Hindu University in 1968. It was designated an Indian Institute of Technology in 2012. IIT (BHU) Varanasi has formerly been known as the Banaras Engineering College (BENCO), the College of Mining and Metallurgy (MINMET), the College of Technology (TECHNO) and the Institute of Technology, Banaras Hindu University (IT-BHU).",

    "The Union Public Service Commission (ISO: Saṅgh Lōk Sēvā Āyōg), commonly abbreviated as UPSC, is India's premier central recruitment agency for recruitment of all the Group 'A' officers under Government of India . It is responsible for appointments to and examinations for all of the Group 'A' posts of all the union government establishments which also includes all of the central public sector units and all of the central autonomous bodies.[1] While Department of Personnel and Training is the central personnel agency in India.",

    "Bhakta Tripathy is the chief editor of News World Odisha. He is a senior television journalist of Odisha, India. He is former editor at ETV News Odia. Before this he was associated with Odisha TV as an input and investigative editor. During his stay at OTV, his special show- the first Odia popular food programme Tasty Tasty was a huge success. This show not only popularized the food culture of the state, but encouraged the state government to induct Tripathy in the Odisha Rasagola research committee.",

    "The 1987 Truro by-election, was caused by the death of David Penhaligon, the Liberal Member of Parliament (MP) for Truro on 22 December 1986 in a car crash near the city. The election was held on 12 March 1987. The constituency was renamed Truro and St Austell in 1997. The candidate succeeding Penhaligon was his then research assistant on the economy, Matthew Taylor, standing with the backing of the Social Democratic Party as part of the SDP-Liberal Alliance.",

    "The Commanding Officer (CO) of the BrahMos unit, which “accidentally fired” the supersonic cruise missile that crashed 124km inside Pakistan on March 9, and a few others are likely to face disciplinary action for the grave operational lapse that could have triggered a retaliation from across the border. The Court of Inquiry (CoI) has held the CO, a Group Captain-rank officer (Colonel), and the others prima facie responsible for the unprecedented incident, sources said on Sunday.",

    `The Chief Justice of India NV Ramana, who will retire on August 26 after a tenure of one year and four months, said that "65 years is too early an age for someone to retire". Chief Justice Ramana was speaking at a virtual session called "Comparative Approaches of Supreme Courts of World's Largest and Oldest Democracies" on Monday.`,

    'He was accompanied on the panel by Justice Stephen Breyer of the US. The session was moderated by William M Treanor, Dean and Executive Vice President, Georgetown University Law Centre. On being asked about the issue of retirement age of judges, Justice Ramana said, "Yes, I think 65 years is too early an age for someone to retire. In the Indian judiciary, at the time of joining we know our date of retirement. There are no exceptions. As for me, I am still left with a decent amount of energy.',
    
    'I am the son of an agriculturalist. I am still left with some land to cultivate. I am basically a man of people. I love to be among the people. It has been my nature since my student days. I hope I will find the right avenue to invest my energy for the sake of people. One thing I can say for certain is that retirement from the judiciary does not mean that I will retire from public life. I am too busy currently to think about my post-retirement plan.',

    `The issue of appointment of more women judges was also a key part of the discussion. The moderator said the Supreme Courts of India and the US are making history with their recent appointment of women judges - appointment of three women Judges in India's Supreme Court last year, and appointment of Justice Ketanji Brown Jackson as the first African-American woman judge in the US Supreme Court.`,

    `Mr Treanor complimented Chief Justice Ramana for the fact that for the first time, a legal professional who is openly gay was recommended by him for elevation to a judge of a constitutional court. Chief Justice Ramana replied, "The first woman judge was appointed in the Supreme Court after nearly 40 years of its establishment. We now have four women judges. This is the highest number so far. I know it is not enough.`,

    `I expect more. I am happy that the recent appointments and recommendations have generated a lot of discussions about inclusivity. In fact I borrowed from Karl Marx to say 'Women of the world, unite. You have nothing to lose but your chains'. This resonated well with the people. They welcomed diversity. For me, inclusivity doesn't stop with having more women judges.`,
    `Our population is nearly 140 crore. The social and geographical diversity must find its reflection at all levels of judiciary. With widest possible representation, people get to feel that it is their own judiciary. Diversity in the bench promotes diversity of opinions. Diversity enhances efficiency. People from different backgrounds enrich the bench with their diverse experiences.`
];